"use client";

import React, { useEffect, useState, useMemo } from "react";
import { useRouter } from "next/navigation";
import { Search, Filter, AlertTriangle, ArrowRight, FileSearch, CheckSquare, Clock, CheckCircle2, XCircle, XSquare } from "lucide-react";
import { cn } from "@/lib/utils";
import { fetchActionRequests, ActionRequestResponse, ActionRequestStatus } from "../../lib/api";

export default function ActionRequestsPage() {
  const [requests, setRequests] = useState<ActionRequestResponse[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const [search, setSearch] = useState("");
  const [statusFilter, setStatusFilter] = useState("ALL");

  const loadData = async () => {
    setLoading(true);
    setError(null);
    try {
      const data = await fetchActionRequests();
      setRequests(data || []);
    } catch (err: any) {
      setError(err.message || "Failed to load action requests");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadData();
  }, []);

  const totalRequests = requests.length;
  const pendingCount = requests.filter(r => r.status === "PENDING_APPROVAL").length;
  const approvedCount = requests.filter(r => r.status === "APPROVED").length;
  const rejectedCount = requests.filter(r => r.status === "REJECTED").length;
  const cancelledCount = requests.filter(r => r.status === "CANCELLED").length;

  const uniqueStatuses = useMemo(() => Array.from(new Set(requests.map(r => r.status))), [requests]);

  const filteredRequests = useMemo(() => {
    return requests.filter(req => {
      if (statusFilter !== "ALL" && req.status !== statusFilter) return false;
      if (search) {
        const q = search.toLowerCase();
        const matches = 
          req.id.toLowerCase().includes(q) || 
          req.investigation_id.toLowerCase().includes(q) ||
          (req.discrepancy_id && req.discrepancy_id.toLowerCase().includes(q)) ||
          req.action.toLowerCase().includes(q);
        if (!matches) return false;
      }
      return true;
    });
  }, [requests, search, statusFilter]);

  const router = useRouter();

  const handleRowClick = (id: string) => {
    router.push(`/action-requests/${id}`);
  };

  const getStatusBadge = (status: ActionRequestStatus) => {
    switch (status) {
      case "APPROVED":
        return <span className="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border border-emerald-500/20">Approved</span>;
      case "REJECTED":
        return <span className="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-rose-500/10 text-rose-600 dark:text-rose-400 border border-rose-500/20">Rejected</span>;
      case "PENDING_APPROVAL":
        return <span className="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-amber-500/10 text-amber-600 dark:text-amber-400 border border-amber-500/20">Pending Approval</span>;
      case "CANCELLED":
        return <span className="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-slate-500/10 text-slate-600 dark:text-slate-400 border border-slate-500/20">Cancelled</span>;
      default:
        return <span className="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-surface-muted text-foreground border border-border">{status}</span>;
    }
  };

  if (loading) {
    return (
      <div className="space-y-6 animate-pulse">
        <div className="h-12 w-1/3 bg-surface-muted rounded"></div>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 sm:gap-6">
          <div className="h-24 bg-surface-muted rounded-xl"></div>
          <div className="h-24 bg-surface-muted rounded-xl"></div>
          <div className="h-24 bg-surface-muted rounded-xl"></div>
          <div className="h-24 bg-surface-muted rounded-xl"></div>
        </div>
        <div className="h-96 w-full bg-surface-muted rounded-xl"></div>
      </div>
    );
  }

  return (
    <div className="space-y-6 animate-in fade-in duration-500 pb-12">
      <div className="flex flex-col gap-2">
        <h1 className="text-page-title">Action Requests</h1>
        <p className="text-secondary max-w-2xl">
          Review and approve financial operation requests generated by the policy engine.
        </p>
      </div>

      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 sm:gap-6">
        <div className="bg-card border border-border shadow-subtle rounded-xl p-5">
          <div className="flex items-center justify-between mb-2">
            <h3 className="text-card-title text-sm">Pending Approval</h3>
            <Clock className="w-4 h-4 text-amber-500" />
          </div>
          <div className="text-kpi">{pendingCount}</div>
          <p className="text-status text-muted-foreground mt-2">Awaiting decision</p>
        </div>

        <div className="bg-card border border-border shadow-subtle rounded-xl p-5">
          <div className="flex items-center justify-between mb-2">
            <h3 className="text-card-title text-sm">Approved</h3>
            <CheckCircle2 className="w-4 h-4 text-emerald-500" />
          </div>
          <div className="text-kpi">{approvedCount}</div>
          <p className="text-status text-muted-foreground mt-2">Action confirmed</p>
        </div>

        <div className="bg-card border border-border shadow-subtle rounded-xl p-5">
          <div className="flex items-center justify-between mb-2">
            <h3 className="text-card-title text-sm">Rejected</h3>
            <XCircle className="w-4 h-4 text-rose-500" />
          </div>
          <div className="text-kpi">{rejectedCount}</div>
          <p className="text-status text-muted-foreground mt-2">Action denied</p>
        </div>

        <div className="bg-card border border-border shadow-subtle rounded-xl p-5">
          <div className="flex items-center justify-between mb-2">
            <h3 className="text-card-title text-sm">Cancelled</h3>
            <XSquare className="w-4 h-4 text-slate-500" />
          </div>
          <div className="text-kpi">{cancelledCount}</div>
          <p className="text-status text-muted-foreground mt-2">Action withdrawn</p>
        </div>
      </div>

      {error ? (
        <div className="p-4 rounded-xl bg-destructive/10 border border-destructive/20 text-destructive flex items-center justify-between shadow-subtle">
          <div className="flex items-center space-x-2">
            <AlertTriangle className="w-5 h-5 shrink-0" />
            <span className="text-sm font-medium">{error}</span>
          </div>
          <button
            onClick={loadData}
            className="px-4 py-1.5 bg-destructive/20 hover:bg-destructive/30 rounded text-sm font-medium transition-colors focus-ring"
          >
            Retry
          </button>
        </div>
      ) : requests.length === 0 ? (
        <div className="flex flex-col items-center justify-center py-32 text-center border border-dashed border-border rounded-xl bg-surface/50 shadow-subtle">
          <CheckSquare className="w-10 h-10 text-muted-foreground/50 mb-4" />
          <h3 className="text-lg font-medium text-foreground mb-2">
            No action requests found
          </h3>
          <p className="text-muted-foreground text-sm max-w-sm">
            There are currently no action requests waiting for approval.
          </p>
        </div>
      ) : (
        <div className="bg-card border border-border shadow-subtle rounded-xl overflow-hidden flex flex-col min-h-[400px]">
          {/* Toolbar */}
          <div className="p-4 sm:p-5 border-b border-border flex flex-col sm:flex-row gap-4 justify-between bg-surface-muted/30">
            <div className="relative w-full sm:max-w-xs">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
              <input
                type="text"
                placeholder="Search requests..."
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                className="w-full pl-9 pr-4 py-2 text-sm bg-surface border border-border rounded-md focus:outline-none focus:ring-2 focus:ring-primary/50 text-foreground placeholder:text-muted-foreground transition-all"
              />
            </div>
            <div className="flex items-center gap-3 w-full sm:w-auto overflow-x-auto pb-1 sm:pb-0">
              <div className="flex items-center space-x-2 shrink-0">
                <Filter className="w-4 h-4 text-muted-foreground" />
                <select
                  value={statusFilter}
                  onChange={(e) => setStatusFilter(e.target.value)}
                  className="text-sm bg-surface border border-border rounded-md px-3 py-2 text-foreground focus:outline-none focus:ring-2 focus:ring-primary/50"
                >
                  <option value="ALL">All Statuses</option>
                  {uniqueStatuses.map((s) => (
                    <option key={s} value={s}>{s}</option>
                  ))}
                </select>
              </div>
            </div>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-surface-muted border-b border-border">
                  <th className="px-5 py-3 text-xs font-medium text-secondary uppercase tracking-wider whitespace-nowrap">ID</th>
                  <th className="px-5 py-3 text-xs font-medium text-secondary uppercase tracking-wider whitespace-nowrap">Action</th>
                  <th className="px-5 py-3 text-xs font-medium text-secondary uppercase tracking-wider whitespace-nowrap">Status</th>
                  <th className="px-5 py-3 text-xs font-medium text-secondary uppercase tracking-wider whitespace-nowrap">Investigation</th>
                  <th className="px-5 py-3 text-xs font-medium text-secondary uppercase tracking-wider whitespace-nowrap text-right">Created</th>
                  <th className="px-5 py-3 text-xs font-medium text-secondary uppercase tracking-wider whitespace-nowrap text-right">Review</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border">
                {filteredRequests.length === 0 ? (
                  <tr>
                    <td colSpan={6} className="px-5 py-8 text-center text-sm text-muted-foreground">
                      No action requests match the current filters. 
                      <button 
                        onClick={() => { setSearch(""); setStatusFilter("ALL"); }} 
                        className="text-primary hover:underline ml-1 font-medium focus-ring rounded"
                      >
                        Clear filters
                      </button>
                    </td>
                  </tr>
                ) : (
                  filteredRequests.map((req) => (
                    <tr key={req.id} onClick={() => handleRowClick(req.id)} className="hover:bg-surface-muted/50 transition-colors group cursor-pointer">
                      <td className="px-5 py-3">
                        <div className="text-xs text-muted-foreground font-mono mt-0.5" title={req.id}>
                          {req.id.substring(0, 8)}...
                        </div>
                      </td>
                      <td className="px-5 py-3">
                        <div className="font-medium text-sm text-foreground bg-surface-muted/50 inline-block px-1.5 py-0.5 rounded border border-border/50">
                          {req.action}
                        </div>
                      </td>
                      <td className="px-5 py-3 whitespace-nowrap">
                        {getStatusBadge(req.status)}
                      </td>
                      <td className="px-5 py-3">
                        <div className="text-xs text-muted-foreground font-mono" title={req.investigation_id}>
                          {req.investigation_id.substring(0, 8)}...
                        </div>
                      </td>
                      <td className="px-5 py-3 text-right font-mono text-xs text-secondary whitespace-nowrap">
                        {req.created_at ? new Date(req.created_at).toLocaleString() : "—"}
                      </td>
                      <td className="px-5 py-3 text-right whitespace-nowrap">
                        <button className="inline-flex items-center justify-center px-3 py-1.5 text-xs font-medium text-primary-foreground bg-primary hover:bg-primary/90 rounded transition-colors focus-ring shadow-sm">
                          Review
                          <ArrowRight className="w-3.5 h-3.5 ml-1.5" />
                        </button>
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  );
}
