"""add reconciliation schema

Revision ID: 5b2a0f1f1825
Revises: 683c739ba187
Create Date: 2026-08-29 07:54:31.005822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b2a0f1f1825'
down_revision: Union[str, Sequence[str], None] = '683c739ba187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciliation_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', name='reconciliationrunstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_records_processed', sa.Integer(), nullable=False),
    sa.Column('matches_created', sa.Integer(), nullable=False),
    sa.Column('discrepancies_found', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discrepancies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('rule_code', sa.String(), nullable=False),
    sa.Column('discrepancy_type', sa.Enum('FEE_MISMATCH', 'AMOUNT_MISMATCH', 'MISSING_BANK_TX', 'MISSING_SETTLEMENT', 'LATE_ARRIVAL', 'CURRENCY_MISMATCH', 'ORPHAN_RECORD', name='discrepancytype'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), nullable=False),
    sa.Column('source_entity_type', sa.String(), nullable=False),
    sa.Column('source_entity_id', sa.String(), nullable=False),
    sa.Column('related_entity_type', sa.String(), nullable=True),
    sa.Column('related_entity_id', sa.String(), nullable=True),
    sa.Column('expected_amount', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('actual_amount', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('difference_amount', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reconciliation_relationships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('source_entity_type', sa.String(), nullable=False),
    sa.Column('source_entity_id', sa.String(), nullable=False),
    sa.Column('target_entity_type', sa.String(), nullable=False),
    sa.Column('target_entity_id', sa.String(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('relationship_status', sa.Enum('CONFIRMED', 'UNRESOLVED', name='relationshipstatus'), nullable=False),
    sa.Column('financial_status', sa.Enum('RECONCILED', 'DISCREPANCY', 'UNRESOLVED', name='financialevaluationstatus'), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliation_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_entity_type', 'source_entity_id', 'target_entity_type', 'target_entity_id', 'relationship_type', name='uq_reconciliation_relationship')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reconciliation_relationships')
    op.drop_table('discrepancies')
    op.drop_table('reconciliation_runs')
    # ### end Alembic commands ###
