"""Add Investigation models

Revision ID: 792f31d86d0d
Revises: 5b2a0f1f1825
Create Date: 2026-08-30 14:28:34.663538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '792f31d86d0d'
down_revision: Union[str, Sequence[str], None] = '5b2a0f1f1825'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('discrepancy_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'UNAVAILABLE', name='investigationstatus'), nullable=False),
    sa.Column('active_attempt_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['active_attempt_id'], ['investigation_attempt.id'], use_alter=True),
    sa.ForeignKeyConstraint(['discrepancy_id'], ['discrepancies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discrepancy_id')
    )
    op.create_table('investigation_attempt',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('prompt_version', sa.String(length=255), nullable=False),
    sa.Column('model_used', sa.String(length=255), nullable=False),
    sa.Column('context_snapshot', sqlite.JSON(), nullable=False),
    sa.Column('context_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_llm_response', sa.String(), nullable=True),
    sa.Column('validated_output', sqlite.JSON(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('validation_errors', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('investigation_attempt')
    op.drop_table('investigation')
    # ### end Alembic commands ###
