"""Add index to is_success on SecurityEvent

Revision ID: 93aca8640b63
Revises: 60e289d97247
Create Date: 2026-09-04 01:33:42.942842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93aca8640b63'
down_revision: Union[str, Sequence[str], None] = '60e289d97247'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_security_events_is_success'), 'security_events', ['is_success'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_events_is_success'), table_name='security_events')
    # ### end Alembic commands ###
