"""feat(auth): add TokenRevocation model

Revision ID: a663d2440b27
Revises: c4a25028244f
Create Date: 2026-09-03 10:01:38.494378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a663d2440b27'
down_revision: Union[str, Sequence[str], None] = 'c4a25028244f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_revocations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_revocations_expires_at'), 'token_revocations', ['expires_at'], unique=False)
    op.create_index(op.f('ix_token_revocations_jti'), 'token_revocations', ['jti'], unique=True)
    op.create_index(op.f('ix_token_revocations_user_id'), 'token_revocations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_revocations_user_id'), table_name='token_revocations')
    op.drop_index(op.f('ix_token_revocations_jti'), table_name='token_revocations')
    op.drop_index(op.f('ix_token_revocations_expires_at'), table_name='token_revocations')
    op.drop_table('token_revocations')
    # ### end Alembic commands ###
