"""add_action_request_models

Revision ID: cd78f7a41f19
Revises: 4571849760fd
Create Date: 2026-09-02 16:51:42.094837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd78f7a41f19'
down_revision: Union[str, Sequence[str], None] = '4571849760fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('discrepancy_id', sa.String(length=36), nullable=True),
    sa.Column('policy_evaluation_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'CANCELLED', name='actionrequeststatus'), nullable=False),
    sa.Column('requested_source', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['discrepancy_id'], ['discrepancies.id'], ),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigation.id'], ),
    sa.ForeignKeyConstraint(['policy_evaluation_id'], ['policy_evaluation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_evaluation_id')
    )
    op.create_table('action_request_audits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('action_request_id', sa.String(length=36), nullable=False),
    sa.Column('previous_status', sa.Enum('PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'CANCELLED', name='actionrequeststatus'), nullable=True),
    sa.Column('new_status', sa.Enum('PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'CANCELLED', name='actionrequeststatus'), nullable=False),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['action_request_id'], ['action_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('action_request_audits')
    op.drop_table('action_requests')
    # ### end Alembic commands ###
